controller_list:
  - name: fake_hera_arm_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_gripper_controller
    joints:
      - finger_1_joint_1
      - finger_1_joint_2
      - finger_2_joint_1
      - finger_2_joint_2
      - finger_middle_joint_1
      - finger_middle_joint_2
initial:  # Define initial robot poses.
  - group: hera_arm
    pose: home
  - group: gripper
    pose: close_gripper