manip:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  
  arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      joint_1: {trajectory: 0.1, goal: 0.1}
      joint_2: {trajectory: 0.1, goal: 0.1}
      joint_3: {trajectory: 0.1, goal: 0.1}
      joint_4: {trajectory: 0.1, goal: 0.1}
      joint_5: {trajectory: 0.1, goal: 0.1}
      joint_6: {trajectory: 0.1, goal: 0.1}
    
    gains: # Required because we're controlling an effort interface
      joint_1: {p: 1000,  d: 0, i: 0, i_clamp: 1}
      joint_2: {p: 1000,  d: 0, i: 0, i_clamp: 1}
      joint_3: {p: 1000,  d: 0, i: 0, i_clamp: 1}
      joint_4: {p: 1000,  d: 0, i: 0, i_clamp: 1}
      joint_5: {p: 1000,  d: 0, i: 0, i_clamp: 1}
      joint_6: {p: 1000,  d: 0, i: 0, i_clamp: 1}
    stop_trajectory_duration: 0.5
    state_publish_rate: 25
    action_monitor_rate: 10

  gripper_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - finger_1_joint_1
      - finger_1_joint_2
      - finger_2_joint_1
      - finger_2_joint_2
      - finger_middle_joint_1
      - finger_middle_joint_2

    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      finger_1_joint_1: {trajectory: 0.1, goal: 0.1}
      finger_1_joint_2: {trajectory: 0.1, goal: 0.1}
      finger_2_joint_1: {trajectory: 0.1, goal: 0.1}
      finger_2_joint_2: {trajectory: 0.1, goal: 0.1}
      finger_middle_joint_1: {trajectory: 0.1, goal: 0.1}
      finger_middle_joint_2: {trajectory: 0.1, goal: 0.1}
    
    gains: # Required because we're controlling an effort interface
      finger_1_joint_1: {p: 1000,  d: 0, i: 0, i_clamp: 1}
      finger_1_joint_2: {p: 1000,  d: 0, i: 0, i_clamp: 1}
      finger_2_joint_1: {p: 1000,  d: 0, i: 0, i_clamp: 1}
      finger_2_joint_2: {p: 1000,  d: 0, i: 0, i_clamp: 1}
      finger_middle_joint_1: {p: 1000,  d: 0, i: 0, i_clamp: 1}
      finger_middle_joint_2: {p: 1000,  d: 0, i: 0, i_clamp: 1}

    stop_trajectory_duration: 0.5
    state_publish_rate: 25
    action_monitor_rate: 10
