#pid que nao treme mas ta mto lerdo (funciona bem no empty.world)
#p:_1.0 
#i:_0.005
#d:_0
manip:
  gazebo_ros_control:
    pid_gains:
      joint_1: {p: 3.768, i: 7.53, d: 1.88}
      joint_2: {p: 3.768, i: 7.53, d: 1.88}
      joint_3: {p: 3.768, i: 7.53, d: 1.88}
      joint_4: {p: 3.768, i: 7.53, d: 1.88}
      joint_5: {p: 3.768, i: 7.53, d: 1.88}
      joint_6: {p: 3.768, i: 7.53, d: 1.88}
      finger_1_joint_1: {p: 3.768, i: 7.53, d: 1.88}
      finger_1_joint_2: {p: 3.768, i: 7.53, d: 1.88}
      finger_2_joint_1: {p: 3.768, i: 7.53, d: 1.88}
      finger_2_joint_2: {p: 3.768, i: 7.53, d: 1.88}
      finger_middle_joint_1: {p: 3.768, i: 7.53, d: 1.88}
      finger_middle_joint_2: {p: 3.768, i: 7.53, d: 1.88}
gazebo_ros_control:
  pid_gains:
    joint_1: {p: 3.768, i: 7.53, d: 1.88}
    joint_2: {p: 3.768, i: 7.53, d: 1.88}
    joint_3: {p: 3.768, i: 7.53, d: 1.88}
    joint_4: {p: 3.768, i: 7.53, d: 1.88}
    joint_5: {p: 3.768, i: 7.53, d: 1.88}
    joint_6: {p: 3.768, i: 7.53, d: 1.88}
    finger_1_joint_1: {p: 3.768, i: 7.53, d: 1.88}
    finger_1_joint_2: {p: 3.768, i: 7.53, d: 1.88}
    finger_2_joint_1: {p: 3.768, i: 7.53, d: 1.88}
    finger_2_joint_2: {p: 3.768, i: 7.53, d: 1.88}
    finger_middle_joint_1: {p: 3.768, i: 7.53, d: 1.88}
    finger_middle_joint_2: {p: 3.768, i: 7.53, d: 1.88}
kinect:
  gazebo_ros_control:
    pid_gains:
      joint_1: {p: 3.768, i: 7.53, d: 1.88}
      joint_2: {p: 3.768, i: 7.53, d: 1.88}
      joint_3: {p: 3.768, i: 7.53, d: 1.88}
      joint_4: {p: 3.768, i: 7.53, d: 1.88}
      joint_5: {p: 3.768, i: 7.53, d: 1.88}
      joint_6: {p: 3.768, i: 7.53, d: 1.88}
      finger_1_joint_1: {p: 3.768, i: 7.53, d: 1.88}
      finger_1_joint_2: {p: 3.768, i: 7.53, d: 1.88}
      finger_2_joint_1: {p: 3.768, i: 7.53, d: 1.88}
      finger_2_joint_2: {p: 3.768, i: 7.53, d: 1.88}
      finger_middle_joint_1: {p: 3.768, i: 7.53, d: 1.88}
      finger_middle_joint_2: {p: 3.768, i: 7.53, d: 1.88}
