#pid que nao treme mas ta mto lerdo (funciona bem no empty.world)
#p:_1.0 
#i:_0.005
#d:_0
manip:
  gazebo_ros_control:
    pid_gains:
      joint_1: {p: 2.7, i: 7.71429, d: 0.23625}
      joint_2: {p: 2.7, i: 7.94118, d: 0.2295}
      joint_3: {p: 2.7, i: 7.71429, d: 0.23625}
      joint_4: {p: 3.3, i: 11.7857, d: 0.231}
      joint_5: {p: 2.7, i: 7.71429, d: 0.23625}
      joint_6: {p: 3.3, i: 11.7857, d: 0.231}
      finger_1_joint_1: {p: 0.0, i: 0.0, d: 0.0}
      finger_1_joint_2: {p: 0.0, i: 0.0, d: 0.0}
      finger_2_joint_1: {p: 0.0, i: 0.0, d: 0.0}
      finger_2_joint_2: {p: 0.0, i: 0.0, d: 0.0}
      finger_middle_joint_1: {p: 0.0, i: 0.0, d: 0.0}
      finger_middle_joint_2: {p: 0.0, i: 0.0, d: 0.0}
gazebo_ros_control:
  pid_gains:
      joint_1: {p: 2.7, i: 7.71429, d: 0.23625}
      joint_2: {p: 2.7, i: 7.94118, d: 0.2295}
      joint_3: {p: 2.7, i: 7.71429, d: 0.23625}
      joint_4: {p: 3.3, i: 11.7857, d: 0.231}
      joint_5: {p: 2.7, i: 7.71429, d: 0.23625}
      joint_6: {p: 3.3, i: 11.7857, d: 0.231}
      finger_1_joint_1: {p: 0.0, i: 0.0, d: 0.0}
      finger_1_joint_2: {p: 0.0, i: 0.0, d: 0.0}
      finger_2_joint_1: {p: 0.0, i: 0.0, d: 0.0}
      finger_2_joint_2: {p: 0.0, i: 0.0, d: 0.0}
      finger_middle_joint_1: {p: 0.0, i: 0.0, d: 0.0}
      finger_middle_joint_2: {p: 0.0, i: 0.0, d: 0.0}
kinect:
  gazebo_ros_control:
    pid_gains:
      joint_1: {p: 2.7, i: 7.71429, d: 0.23625}
      joint_2: {p: 2.7, i: 7.94118, d: 0.2295}
      joint_3: {p: 2.7, i: 7.71429, d: 0.23625}
      joint_4: {p: 3.3, i: 11.7857, d: 0.231}
      joint_5: {p: 2.7, i: 7.71429, d: 0.23625}
      joint_6: {p: 3.3, i: 11.7857, d: 0.231}
      finger_1_joint_1: {p: 0.0, i: 0.0, d: 0.0}
      finger_1_joint_2: {p: 0.0, i: 0.0, d: 0.0}
      finger_2_joint_1: {p: 0.0, i: 0.0, d: 0.0}
      finger_2_joint_2: {p: 0.0, i: 0.0, d: 0.0}
      finger_middle_joint_1: {p: 0.0, i: 0.0, d: 0.0}
      finger_middle_joint_2: {p: 0.0, i: 0.0, d: 0.0}
