controller_list:
  - name: manip/arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: manip/gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - finger_1_joint_1
      - finger_1_joint_2
      - finger_2_joint_1
      - finger_2_joint_2
      - finger_middle_joint_1
      - finger_middle_joint_2